// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  item_name: string
  current_room?: string | null
  table_name?: string | null
  system_name?: string | null
  current_owner_id?: string | null
  taken_at?: string | null
  item_img_url?: string | null
  item_vendor?: string | null
  item_params?: string | null
  is_available?: boolean
}

export type ItemPublic = {
  item_id: string
  item_name: string
  current_room?: string | null
  table_name?: string | null
  system_name?: string | null
  current_owner_id?: string | null
  taken_at?: string | null
  item_img_url?: string | null
  item_vendor?: string | null
  item_params?: string | null
  is_available?: boolean
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  item_name?: string | null
  item_img_url?: string | null
  item_vendor?: string | null
  item_params?: string | null
}

export type ItemTake = {
  table_name?: string | null
  current_room?: string | null
  system_name?: string | null
  current_owner_id?: string | null
  taken_at?: string | null
  is_available?: boolean
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  user_id: string
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  is_part_of_lab?: boolean
  can_edit_items?: boolean
  can_edit_labs?: boolean
  can_edit_users?: boolean
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type UserPermissionsUpdate = {
  is_part_of_lab?: boolean | null
  can_edit_items?: boolean | null
  can_edit_labs?: boolean | null
  can_edit_users?: boolean | null
}

export type RoomBase = {
  room_number: string;
  room_place: string;
  room_owner_id: string;
}

// RoomCreate
export type RoomCreate = RoomBase;

// RoomUpdate
export type RoomUpdate = {
  room_number?: string | null;
  room_place?: string | null;
  room_owner_id: string;
}

// RoomPublic
export type RoomPublic = RoomBase & {
  room_id: string;
}

// RoomsPublic
export type RoomsPublic = {
  data: Array<RoomPublic>;
  count: number;
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  item_id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  item_id: string
  requestBody: ItemUpdate
}

export type ItemTakeItemResponse = ItemPublic

export type ItemTakeItemData = {
  item_id: string
  requestBody: ItemTake
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  item_id: string
}

export type ItemsDeleteItemResponse = Message

export type RoomsReadRoomsData = {
  limit?: number
  skip?: number
}

export type RoomsReadRoomsResponse = RoomsPublic

export type RoomsCreateRoomData = {
  requestBody: RoomCreate
}

export type RoomsCreateRoomResponse = RoomPublic

export type RoomsReadRoomData = {
  room_id: string
}

export type RoomsReadRoomResponse = RoomPublic

export type RoomsUpdateRoomData = {
  room_id: string
  requestBody: RoomUpdate
}

export type RoomsUpdateRoomResponse = RoomPublic

export type RoomsDeleteRoomData = {
  room_id: string
}

export type RoomsDeleteRoomResponse = Message


export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  user_id: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  user_id: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  user_id: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean