"""Add cascade delete relationships

Revision ID: 1a31ce608336
Revises: d98dd8ec85a3
Create Date: 2024-07-31 22:24:34.447891

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1a31ce608336'
down_revision = 'd98dd8ec85a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure the 'current_owner_id' column in 'item' is not nullable
    op.alter_column('item', 'current_owner_id',
                    existing_type=sa.UUID(),
                    nullable=False)

    # Drop the existing foreign key constraint for 'item'
    op.drop_constraint('item_current_owner_id_fkey', 'item', type_='foreignkey')

    # Create a new foreign key constraint with ON DELETE CASCADE for 'item'
    op.create_foreign_key(
        'item_current_owner_id_fkey',
        'item', 'user',
        ['current_owner_id'], ['user_id'],
        ondelete='CASCADE'
    )

    # Ensure the 'room_owner_id' column in 'room' is not nullable
    op.alter_column('room', 'room_owner_id',
                    existing_type=sa.UUID(),
                    nullable=False)

    # Drop the existing foreign key constraint for 'room'
    op.drop_constraint('room_room_owner_id_fkey', 'room', type_='foreignkey')

    # Create a new foreign key constraint with ON DELETE CASCADE for 'room'
    op.create_foreign_key(
        'room_room_owner_id_fkey',
        'room', 'user',
        ['room_owner_id'], ['user_id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint with ON DELETE CASCADE for 'item'
    op.drop_constraint('item_current_owner_id_fkey', 'item', type_='foreignkey')

    # Recreate the original foreign key constraint without ON DELETE CASCADE for 'item'
    op.create_foreign_key(
        'item_current_owner_id_fkey',
        'item', 'user',
        ['current_owner_id'], ['user_id']
    )

    # Revert the 'current_owner_id' column to nullable for 'item'
    op.alter_column('item', 'current_owner_id',
                    existing_type=sa.UUID(),
                    nullable=True)

    # Drop the foreign key constraint with ON DELETE CASCADE for 'room'
    op.drop_constraint('room_room_owner_id_fkey', 'room', type_='foreignkey')

    # Recreate the original foreign key constraint without ON DELETE CASCADE for 'room'
    op.create_foreign_key(
        'room_room_owner_id_fkey',
        'room', 'user',
        ['room_owner_id'], ['user_id']
    )

    # Revert the 'room_owner_id' column to nullable for 'room'
    op.alter_column('room', 'room_owner_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###